services:
  fdb-server:
    image: foundationdb/foundationdb:7.3.42
    entrypoint: ["/bin/bash", "/var/fdb/scripts/fdb_single.bash"]
    environment:
      FDB_NETWORKING_MODE: 'container'
      FDB_CLUSTER_FILE: '/etc/foundationdb/fdb.cluster'
      FDB_CLUSTER_FILE_CONTENTS: 'docker:4500@fdb-server:4500'
    volumes:
      - "fdb-config:/etc/foundationdb"
      - "fdb-data:/var/fdb/data"
      - "fdb-logs:/var/fdb/logs"

  mgmt-server:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: "uvicorn simplyblock_web.api:public --root-path=/api --log-level=debug"
    volumes:
      - "fdb-config:/etc/foundationdb"
    environment:
      - FLASK_DEBUG=False
      - FLASK_ENV=production
    depends_on:
      - fdb-server

  storage-node:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: "python simplyblock_web/node_webapp.py storage_node"
    environment:
      - FLASK_DEBUG=False
      - FLASK_ENV=production
    depends_on:
      - fdb-server

volumes:
  fdb-data:
  fdb-logs:
  fdb-config:
