[build-system]
requires = ['setuptools>70']
build-backend = 'setuptools.build_meta'

[tool.ruff]
extend-exclude = ['simplyblock_cli/cli.py']

[tool.mypy]
check_untyped_defs = true

[tool.pytest.ini_options]
pythonpath = "."
testpaths = ['simplyblock_core/test', 'simplyblock_web/test']
