apiVersion: apps/v1
kind: Deployment
metadata:
  name: caching-node-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caching-node-api
  template:
    metadata:
      labels:
        app: caching-node-api
    spec:
      hostNetwork: true
      containers:
      - name: c-node-api-container
        image: hamdykhader/simplyblock:latest
        imagePullPolicy: "Always"
        command: ["python", "simplyblock_web/node_webapp.py", "caching_kubernetes_node"]
        securityContext:
          privileged: true
