# postgres-vm.yaml
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: postgres-vm
spec:
  running: true
  template:
    metadata:
      labels:
        app: postgres
    spec:
      evictionStrategy: LiveMigrate
      domain:
        devices:
          disks:
            - disk:
                bus: virtio
              name: rootdisk
            - disk:
                bus: virtio
              name: datadisk # Disk for PostgreSQL data
          interfaces:
            - name: default
              masquerade: {}
        resources:
          requests:
            memory: 2Gi # Adjust memory as needed
        cpu:
          cores: 2 # Adjust CPU cores as needed
      networks:
        - name: default
          pod: {}
      volumes:
        - name: rootdisk
          containerDisk:
            image: rrukmantiyo/kubevirt-images:ubuntu-22.04 # Changed to Ubuntu 22.04 image
        - name: datadisk
          persistentVolumeClaim:
            claimName: postgres-data-pvc
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              hostname: postgres-vm
                users:
                  - name: cloud-user
                    groups: wheel
                    sudo: ALL=(ALL) NOPASSWD:ALL
                    shell: /bin/bash
                    passwd: "$6$FmygXsJk$x5K5ZWxzNcd7kE5XaPY0UMC8yWTQAPOIvYkJmdrxA5D01zmDjhMJ7Z3Wj6rYhsxtVzLPXAV1eQCE6WZ2BS5Ub0"
                    ssh-authorized-keys:
                      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCUB/sc4zU36OrPIFxV2UPZWGdzgg7+0HgqmmrSJIEuSMtXfNeyCDuV40JCqmmKX1vuQ7Df36IK9vR5KlBcM6K+PDwpjnd1xLfgnecqL5LxtqZTJSWc/oV2irA6JgtMIFgNX2S+DhwdyfxLG8dxyW1iKDzBgWANP+phk8WQfR13UBpdmzKYalbMLIsN87O12Ua1fF1KH5Qq0mVCPZnncCrJZCcHy9gYkxaXdcMtfRdmlVTjaZ8Z6RJ8G5RNfOywNMXAOJsbHSu609VTtqszLjeRJz21mhVWzLWYwk8PgBLkptwMHKGc6dMVC42jalXHWw5Qr7rlyoPoIeUMtMSQl/9FtMJgAawnKQNZmX00zyjXrWAz+SfZvp2z0dgQ8epgzaznewznXxnbnSjbaOU8WNr4/EdfNv/gUyCJM5Hm1Y6l1FRYOJpGarV6qa9eCEJP0WqD4BzQZNl1/h51xv2MwHncCw6NzGYMkUoInlR0WAZ/XyMZwLcwY2ZpvYyr9XldmiE= root@vm06.simplyblock5.localdomain

              runcmd:
                # Install PostgreSQL on Ubuntu/Debian
                - apt-get update -y
                - apt-get install -y postgresql postgresql-contrib
                - systemctl enable postgresql
                - systemctl start postgresql

                # Configure PostgreSQL to listen on all interfaces
                - sed -i "s/#listen_addresses = 'localhost'/listen_addresses = '*'/" /etc/postgresql/14/main/postgresql.conf # Adjust version if needed
                - echo "host    all             all             0.0.0.0/0               md5" >> /etc/postgresql/14/main/pg_hba.conf # Adjust version if needed

                # Create a database and user
                - sudo -u postgres psql -c "CREATE DATABASE mydatabase;"
                - sudo -u postgres psql -c "CREATE USER myuser WITH ENCRYPTED PASSWORD 'mypassword';" # CHANGE THIS PASSWORD!
                - sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE mydatabase TO myuser;"

                - systemctl restart postgresql
