# postgres-vm.yaml
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: postgres-vm
spec:
  runStrategy: "Always"
  template:
    metadata:
      labels:
        app: postgres
    spec:
      evictionStrategy: LiveMigrate
      domain:
        devices:
          disks:
            - disk:
                bus: virtio
              name: rootdisk
            - disk:
                bus: virtio
              name: datadisk
          interfaces:
            - name: default
              masquerade: {}
        memory: 
          guest: 2Gi
        cpu:
          cores: 2
      networks:
        - name: default
          pod: {}
      volumes:
        - name: rootdisk
          containerDisk:
            image: quay.io/containerdisks/fedora:latest # Changed to Ubuntu 22.04 image
        - name: datadisk
          persistentVolumeClaim:
            claimName: postgres-data-pvc
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              password: fedora
              ssh_pwauth: True
              chpasswd: { expire: False }
              runcmd:
                - lsblk
                - df -h

                # - mkdir -p /mnt/data

                # - |
                #   if ! blkid /dev/vdb; then
                #     mkfs -t ext4 /dev/vdb
                #   fi

                # - mount /dev/vdb /mnt/data
                # - lsblk
                # - df -h
