# postgres-vm.yaml
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: postgres-vm
spec:
  running: true
  template:
    metadata:
      labels:
        app: postgres
    spec:
      evictionStrategy: LiveMigrate
      domain:
        devices:
          disks:
            - disk:
                bus: virtio
              name: rootdisk
            - disk:
                bus: virtio
              name: datadisk # Disk for PostgreSQL data
          interfaces:
            - name: default
              masquerade: {}
        resources:
          requests:
            memory: 2Gi # Adjust memory as needed
        cpu:
          cores: 2 # Adjust CPU cores as needed
      networks:
        - name: default
          pod: {}
      volumes:
        - name: rootdisk
          containerDisk:
            image: rrukmantiyo/kubevirt-images:ubuntu-22.04 # Changed to Ubuntu 22.04 image
        - name: datadisk
          persistentVolumeClaim:
            claimName: postgres-data-pvc
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              hostname: postgres-vm
              users:
                - name: cloud-user
                  groups: wheel
                  sudo: ALL=(ALL) NOPASSWD:ALL

              runcmd:
                # Install PostgreSQL on Ubuntu/Debian
                - apt-get update -y
                - apt-get install -y postgresql postgresql-contrib
                - systemctl enable postgresql
                - systemctl start postgresql

                # Configure PostgreSQL to listen on all interfaces
                - sed -i "s/#listen_addresses = 'localhost'/listen_addresses = '*'/" /etc/postgresql/14/main/postgresql.conf # Adjust version if needed
                - echo "host    all             all             0.0.0.0/0               md5" >> /etc/postgresql/14/main/pg_hba.conf # Adjust version if needed

                # Create a database and user
                - sudo -u postgres psql -c "CREATE DATABASE mydatabase;"
                - sudo -u postgres psql -c "CREATE USER myuser WITH ENCRYPTED PASSWORD 'mypassword';" # CHANGE THIS PASSWORD!
                - sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE mydatabase TO myuser;"

                - systemctl restart postgresql
