apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: testvm
spec:
  runStrategy: Halted
  template:
    metadata:
      labels:
        kubevirt.io/size: small
        kubevirt.io/domain: testvm
    spec:
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
            - disk:
                bus: virtio
              name: datadisk
          interfaces:
          - name: default
            masquerade: {}
        memory:
          guest: 1G 
      networks:
      - name: default
        pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/containerdisks/fedora:latest 
        - name: datadisk
          persistentVolumeClaim:
            claimName: postgres-data-pvc
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              password: fedora
              ssh_pwauth: True
              chpasswd: { expire: False }
              runcmd:
                - lsblk
                - df -h

                # - mkdir -p /mnt/data

                # - |
                #   if ! blkid /dev/vdb; then
                #     mkfs -t ext4 /dev/vdb
                #   fi

                # - mount /dev/vdb /mnt/data
                # - lsblk
                # - df -h
