---
apiVersion: v1
appVersion: latest
description: Simplyblock Control Plane
name: sbcli
version: "v0.1.0"
keywords:
- simplyblock
- mgmt
- sbcli
home: https://github.com/simplyblock-io/sbcli
sources:
- https://github.com/simplyblock-io/sbcli/tree/main/simplyblock_core/scripts/charts

dependencies:
  - name: openebs
    version: 3.9.0 
    repository: https://openebs.github.io/charts
    alias: openebs
    condition: openebs.enabled
    