version: '3.8'

services:
  fdb-server:
    image: foundationdb/foundationdb:7.3.2
    networks:
      - hostnet
    environment:
      SIMPLYBLOCK_LOG_LEVEL: '$LOG_LEVEL'
      FDB_CLUSTER_FILE_CONTENTS: '$FDB_CLUSTER_FILE_CONTENTS'
      FDB_NETWORKING_MODE: 'container'
      FDB_CLUSTER_FILE: '/etc/foundationdb/fdb.cluster'
    volumes:
      - "/etc/foundationdb:/etc/foundationdb"
      - "/etc/foundationdb/data:/var/fdb/data"
      - "/etc/foundationdb/logs:/var/fdb/logs"

    deploy:
      mode: global
      placement:
        constraints: [ node.role == manager ]

  WebAppAPI:
    image: $SIMPLYBLOCK_DOCKER_IMAGE
    command: "python simplyblock_web/app.py"
    networks:
      - localnet
    deploy:
      endpoint_mode: dnsrr
      mode: global
      placement:
        constraints: [node.role == manager]
    volumes:
      - "/etc/foundationdb:/etc/foundationdb"
    environment:
      SIMPLYBLOCK_LOG_LEVEL: "$LOG_LEVEL"
      FLASK_DEBUG: "False"
      FLASK_ENV: "production"

  StorageNodeMonitor:
    image: $SIMPLYBLOCK_DOCKER_IMAGE
    command: "python simplyblock_core/services/storage_node_monitor.py"
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - "/etc/foundationdb:/etc/foundationdb"
    networks:
      - hostnet
    environment:
      SIMPLYBLOCK_LOG_LEVEL: "$LOG_LEVEL"

  MgmtNodeMonitor:
    image: $SIMPLYBLOCK_DOCKER_IMAGE
    command: "python simplyblock_core/services/mgmt_node_monitor.py"
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - "/etc/foundationdb:/etc/foundationdb"
    networks:
      - hostnet
    environment:
      SIMPLYBLOCK_LOG_LEVEL: "$LOG_LEVEL"

  CachingNodeMonitor:
    image: $SIMPLYBLOCK_DOCKER_IMAGE
    command: "python simplyblock_core/services/caching_node_monitor.py"
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - "/etc/foundationdb:/etc/foundationdb"
    networks:
      - hostnet
    environment:
      SIMPLYBLOCK_LOG_LEVEL: "$LOG_LEVEL"

  LVolStatsCollector:
    image: $SIMPLYBLOCK_DOCKER_IMAGE
    command: "python simplyblock_core/services/lvol_stat_collector.py"
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - "/etc/foundationdb:/etc/foundationdb"
    networks:
      - hostnet
    environment:
      SIMPLYBLOCK_LOG_LEVEL: "$LOG_LEVEL"

  CachedLVolStatsCollector:
    image: $SIMPLYBLOCK_DOCKER_IMAGE
    command: "python simplyblock_core/services/cached_lvol_stat_collector.py"
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - "/etc/foundationdb:/etc/foundationdb"
    networks:
      - hostnet
    environment:
      SIMPLYBLOCK_LOG_LEVEL: "$LOG_LEVEL"

  MainDistrEventCollector:
    image: $SIMPLYBLOCK_DOCKER_IMAGE
    command: "python simplyblock_core/services/main_distr_event_collector.py"
    networks:
      - hostnet
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - "/etc/foundationdb:/etc/foundationdb"
    environment:
      SIMPLYBLOCK_LOG_LEVEL: "$LOG_LEVEL"

  HAProxy:
    image: haproxytech/haproxy-debian:latest
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]
    ports:
      - 80:80
      - 12202:12202
    networks:
      - localnet
      - monitoring-net
    volumes:
      - "$DIR/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg"
    environment:
      SIMPLYBLOCK_LOG_LEVEL: "$LOG_LEVEL"

  CapacityAndStatsCollector:
    image: $SIMPLYBLOCK_DOCKER_IMAGE
    command: "python simplyblock_core/services/capacity_and_stats_collector.py"
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - "/etc/foundationdb:/etc/foundationdb"
    networks:
      - hostnet
    environment:
      SIMPLYBLOCK_LOG_LEVEL: "$LOG_LEVEL"

  CapacityMonitor:
    image: $SIMPLYBLOCK_DOCKER_IMAGE
    command: "python simplyblock_core/services/cap_monitor.py"
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - "/etc/foundationdb:/etc/foundationdb"
    networks:
      - hostnet
    environment:
      SIMPLYBLOCK_LOG_LEVEL: "$LOG_LEVEL"

  HealthCheck:
    image: $SIMPLYBLOCK_DOCKER_IMAGE
    command: "python simplyblock_core/services/health_check_service.py"
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - "/etc/foundationdb:/etc/foundationdb"
    networks:
      - hostnet
    environment:
      SIMPLYBLOCK_LOG_LEVEL: "$LOG_LEVEL"

  DeviceMonitor:
    image: $SIMPLYBLOCK_DOCKER_IMAGE
    command: "python simplyblock_core/services/device_monitor.py"
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - "/etc/foundationdb:/etc/foundationdb"
    networks:
      - hostnet
    environment:
      SIMPLYBLOCK_LOG_LEVEL: "$LOG_LEVEL"

  LVolMonitor:
    image: $SIMPLYBLOCK_DOCKER_IMAGE
    command: "python simplyblock_core/services/lvol_monitor.py"
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - "/etc/foundationdb:/etc/foundationdb"
    networks:
      - hostnet
    environment:
      SIMPLYBLOCK_LOG_LEVEL: "$LOG_LEVEL"

  CleanupFDB:
    image: $SIMPLYBLOCK_DOCKER_IMAGE
    environment:
      SIMPLYBLOCK_LOG_LEVEL: "$LOG_LEVEL"
      LOG_DELETION_INTERVAL: "${LOG_DELETION_INTERVAL}"
    command: "python simplyblock_core/workers/cleanup_foundationdb.py"
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - "/etc/foundationdb:/etc/foundationdb"
    networks:
      - hostnet

  TasksRunnerRestart:
    image: $SIMPLYBLOCK_DOCKER_IMAGE
    command: "python simplyblock_core/services/tasks_runner_restart.py"
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - "/etc/foundationdb:/etc/foundationdb"
    networks:
      - hostnet
    environment:
      SIMPLYBLOCK_LOG_LEVEL: "$LOG_LEVEL"

  TasksRunnerMigration:
    image: $SIMPLYBLOCK_DOCKER_IMAGE
    command: "python simplyblock_core/services/tasks_runner_migration.py"
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - "/etc/foundationdb:/etc/foundationdb"
    networks:
      - hostnet
    environment:
      SIMPLYBLOCK_LOG_LEVEL: "$LOG_LEVEL"

  TasksRunnerFailedMigration:
    image: $SIMPLYBLOCK_DOCKER_IMAGE
    command: "python simplyblock_core/services/tasks_runner_failed_migration.py"
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - "/etc/foundationdb:/etc/foundationdb"
    networks:
      - hostnet
    environment:
      SIMPLYBLOCK_LOG_LEVEL: "$LOG_LEVEL"

  TasksRunnerNewDeviceMigration:
    image: $SIMPLYBLOCK_DOCKER_IMAGE
    command: "python simplyblock_core/services/tasks_runner_new_dev_migration.py"
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - "/etc/foundationdb:/etc/foundationdb"
    networks:
      - hostnet
    environment:
      SIMPLYBLOCK_LOG_LEVEL: "$LOG_LEVEL"

  NewDeviceDiscovery:
    image: $SIMPLYBLOCK_DOCKER_IMAGE
    command: "python simplyblock_core/services/new_device_discovery.py"
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - "/etc/foundationdb:/etc/foundationdb"
    networks:
      - hostnet
    environment:
      SIMPLYBLOCK_LOG_LEVEL: "$LOG_LEVEL"

  TasksNodeAddRunner:
    image: $SIMPLYBLOCK_DOCKER_IMAGE
    command: "python simplyblock_core/services/tasks_runner_node_add.py"
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - "/etc/foundationdb:/etc/foundationdb"
    networks:
      - hostnet
    environment:
      SIMPLYBLOCK_LOG_LEVEL: "$LOG_LEVEL"


volumes:
  os_data:

networks:
  monitoring-net:
    external: true

  hostnet:
    external: true
    name: host

  localnet:
    driver: overlay
    ipam:
      config:
        - subnet: 192.168.1.0/24
