global:
  scrape_interval: 30s
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'metricsgateway'
    static_configs:
      - targets: ['pushgateway:9091']
      
  - job_name: 'node'
    dns_sd_configs:
    - names:
      - 'tasks.node-exporter'
      type: 'A'
      port: 9100
