name: API Test

on:
  workflow_call:
    inputs:
      runs_on:  # Has to be an input
        description: Platform to execute on
        type: string
        default: ubuntu-latest
      cluster_ip:
        required: true
        type: string
      cluster_id:
        required: true
        type: string
      cluster_secret:
        required: true
        type: string

jobs:
  api_test:
    runs-on: ${{ inputs.runs_on }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        pip3 install -r test-requirements.txt

    - name: Run tests
      run: |
        pytest -v simplyblock_web \
          --entrypoint=${{ inputs.cluster_ip }} \
          --cluster=${{ inputs.cluster_id }} \
          --secret=${{ inputs.cluster_secret }}

    - name: Retrieve API logs
      if: ${{ always() }}
      run: >-
        curl \
            -u admin:${{ inputs.cluster_secret }} \
            -H "Accept: application/json" \
            "${{ inputs.cluster_ip }}/graylog/api/search/universal/relative?query=container_name:app_WebAppAPI.*&limit=10000" \
          | jq -r '.messages | map(.message) | map(.message) | join("\n")' \
          > api.log

    - name: 'Upload artifact'
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: api-log
        path: api.log
        retention-days: 30
