name: Deploy and test cluster

on:
  workflow_dispatch:
    inputs:
      cluster:
        description: 'Cluster identifier'
        required: true
      docker_image:
        description: 'Docker image'
        default: 'public.ecr.aws/simply-block/simplyblock:main'
        required: false

permissions:
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/bare-metal-deploy.yml
    with:
      runs_on: self-hosted
      cluster: ${{ github.event.inputs.cluster }}
      docker_image: ${{ github.event.inputs.docker_image }}
      sbcli_source: ${{ github.ref_name }}

  test:
    needs: deploy
    uses: ./.github/workflows/api-test.yml
    with:
      runs_on: self-hosted
      cluster_id: ${{ needs.deploy.outputs.cluster_id }}
      cluster_ip: ${{ needs.deploy.outputs.cluster_ip }}
      cluster_secret: ${{ needs.deploy.outputs.cluster_secret }}
