name: Docker Image Build

on:
  workflow_dispatch:
  push:
    branches:
      - '**'


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set docker image tag
      id: get_info
      run: |
        if [[ "${{github.ref}}" == refs/pull/* ]]; then
          tag=${GITHUB_REF/\/merge/}
          echo "TAG=$(echo pr-${tag:10})" >> $GITHUB_ENV
        else
          echo "TAG=$(echo ${GITHUB_REF#refs/*/} | sed 's/\//-/g')" >> $GITHUB_ENV
        fi
        echo "BRANCH=$([ -z '${{ github.event.pull_request.head.sha }}' ] && echo ${GITHUB_REF#refs/*/} || echo $GITHUB_HEAD_REF)" >> $GITHUB_ENV
        echo "SHA=$([ -z '${{ github.event.pull_request.head.sha }}' ] && echo $GITHUB_SHA || echo '${{ github.event.pull_request.head.sha }}')" >> $GITHUB_ENV

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: hamdysimplyblock
        password: ${{ secrets.DOCKER_PASS }}

    - name: Build & Push
      run: |
        SHORT_SHA=$(echo ${{ env.SHA }} | head -c 8)

        sudo apt-get update -y
        sudo apt-get install -y qemu-system qemu-user-static
        docker buildx ls
        docker buildx create --name mybuilder --bootstrap --use
        docker buildx build --platform linux/amd64,linux/arm64 -t simplyblock/simplyblock:$TAG -f docker/Dockerfile . --push
        docker buildx build --platform linux/amd64,linux/arm64 -t simplyblock/simplyblock:$TAG-$SHORT_SHA -f docker/Dockerfile . --push

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_HAMDI }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_HAMDI }}
        aws-region: us-east-1

    - name: Login to ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Push the docker image
      run: |
        docker buildx build --platform linux/amd64,linux/arm64 -t 565979732541.dkr.ecr.us-east-1.amazonaws.com/simplyblock:$TAG -f docker/Dockerfile . --push
