name: Docker Image Build

on:
  workflow_dispatch:
  push:
    branches:
      - '**'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout project
      uses: actions/checkout@master

    - name: Set docker image tag
      id: image_info
      run: |
        if [[ "${{ github.ref }}" == refs/pull/* ]]; then
          tag=${GITHUB_REF/\/merge/}
          echo "tag=$(echo pr-${tag:10})" >> $GITHUB_OUTPUT
        else
          echo "tag=$(echo ${GITHUB_REF#refs/*/} | sed 's/\//-/g')" >> $GITHUB_OUTPUT
        fi
        echo "short_sha=$(echo ${{ github.sha }} | head -c 8)" >> $GITHUB_OUTPUT

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: hamdysimplyblock
        password: ${{ secrets.DOCKER_PASS }}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_HAMDI }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_HAMDI }}
        aws-region: us-east-1

    - name: Login to ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      with:
        registry-type: public

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Build and publish image
      uses: docker/build-push-action@v6
      with:
        file: docker/Dockerfile
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          simplyblock/simplyblock:${{ steps.image_info.outputs.tag }}
          simplyblock/simplyblock:${{ steps.image_info.outputs.tag }}-${{ steps.image_info.outputs.short_sha }}
          public.ecr.aws/simply-block/simplyblock:${{ steps.image_info.outputs.tag }}
          public.ecr.aws/simply-block/simplyblock:${{ steps.image_info.outputs.tag }}-${{ steps.image_info.outputs.short_sha }}
        cache-from: type=registry,ref=simplyblock/simplyblock:${{ steps.image_info.outputs.tag }}
        cache-to: type=registry,ref=simplyblock/simplyblock:${{ steps.image_info.outputs.tag }},mode=max
