name: Docker Image Build

on:
  workflow_dispatch:
  push:
    branches:
      - '**'


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set docker image tag
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          simplyblock/simplyblock
          public.ecr.aws/simply-block/simplyblock
        tags: |
          type=raw,value=latest,enable={{ is_default_branch }}
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{ branch }}-

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: hamdysimplyblock
        password: ${{ secrets.DOCKER_PASS }}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_HAMDI }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_HAMDI }}
        aws-region: us-east-1

    - name: Login to ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      with:
        registry-type: public

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Build & Push
      uses: docker/build-push-action@v6
      with:
        file: docker/Dockerfile
        platforms: linux/amd64,linux/arm64
        tags: ${{ steps.meta.outputs.tags }}
        push: true
      cache-to: type=gha
      cache-from: type=gha,mode=max
