name: Docker Image Build

on:
  workflow_dispatch:
  push:
    branches:
      - '**'


jobs:
  build:
    uses: ./.github/workflows/build-docker-image.yml
    with:
      dockerfile: docker/Dockerfile
      images: |
        simplyblock/simplyblock
        public.ecr.aws/simply-block/simplyblock
      tags: |
        type=raw,value=latest,enable={{ is_default_branch }}
        type=ref,event=branch
        type=ref,event=pr
        type=sha,prefix={{ branch }}-
