name: Docker Base Image Build

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-docker-image.yml
    with:
      dockerfile: docker/Dockerfile_base
      images: |
        simplyblock/simplyblock
        public.ecr.aws/simply-block/simplyblock
      tags: |
        type=raw,value=base_image,enable={{ is_default_branch }}
    secrets: inherit
