name: Integration Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  integration-test:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:24.0.5
        options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v2

      - name: Build and start containers
        run: |
          docker compose -f docker-compose-dev.yml up --build -d

      - name: Run endpoint checks inside mgmt-server
        run: |
          docker compose -f docker-compose-dev.yml exec mgmt-server python manual_testing/check_endpoints.py

      - name: Stop and clean up
        if: always()
        run: |
          docker compose -f docker-compose-dev.yml down --volumes --remove-orphans
