name: Python checks 

on:
  pull_request

permissions:
  contents: read

jobs:
  clipy-test:
    name: Ensure cli.py is up to date
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        cache: 'pip'

    - name: Checking cli.py status
      run: |
        ./simplyblock_cli/scripts/generate.sh
        changes="$(git diff simplyblock_cli/cli.py)"
        if [[ "${changes}" ]]; then
          echo "cli.py has changed after regeneration. Stopping."
          echo "${changes}"
          exit 1
        fi


  test:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        cache: 'pip'

    - name: Install test dependencies
      run: pip install -r requirements.txt

    - name: Install package
      run: pip install .

    - name: Run tests
      run: pytest -v


  lint:
    name: Linter
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        cache: 'pip'

    - name: Install linter
      run: pip install ruff

    - name: Execute linter
      run: ruff check simplyblock_core simplyblock_web simplyblock_cli e2e testing
