name: Python Package Build

on:
  pull_request:
    branches:
      - '**'

permissions:
  contents: read

jobs:
  clipy-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip twine setuptools
        pip install build
    - name: Checking cli.py status
      run: |
        ./scripts/generate.sh
        changes="$(git diff simplyblock_cli/cli.py)"
        if [[ "${changes}" ]]; then
          echo "cli.py has changed after regeneration. Stopping."
          echo "${changes}"
          exit 1
        fi
