name: Python Type Checker

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools build
        pip install -r requirements.txt
        pip install mypy

    - name: Install package
      run: python setup.py install

    - name: Run type checker
      run: |
        mypy simplyblock_core simplyblock_web simplyblock_cli
