name: Release
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      - name: Checking cli.py status
        run: |
          ./scripts/generate.sh
          changes="$(git diff simplyblock_cli/cli.py)"
          if [[ "${changes}" ]]; then
            echo "cli.py has changed after regeneration. Stopping."
            echo "${changes}"
            exit 1
          fi

      - name: Update simplyblock_core/env_var
        run: |
          sed -i 's/sbcli/sbcli-pre/g' simplyblock_core/env_var
          version="${{ github.event.release.tag_name }}"
          echo "Replacing SIMPLY_BLOCK_VERSION with $version"
          sed -i "s/^SIMPLY_BLOCK_VERSION=.*/SIMPLY_BLOCK_VERSION=${version}/" simplyblock_core/env_var

      - name: Build package
        run: python setup.py sdist

      - name: Publish package to pypi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
